version: '3.8'

services:
  web:
    # Construye la imagen usando el Dockerfile en el directorio actual
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    container_name: voltrace_app