# ===================================================================
# CONFIGURACIÓN GLOBAL - VOLTRACE (game_config.py)
# ===================================================================
# Este archivo centraliza todos los valores de balanceo y configuración
# del juego para facilitar ajustes rápidos sin tocar la lógica.
# ===================================================================

# --- CONFIGURACIÓN GENERAL DEL JUEGO ---
ENERGIA_INICIAL = 600
POSICION_META = 75
MID_GAME_RONDA = 15 
DURACION_TURNO_SEGUNDOS = 90
MAX_JUGADORES = 4
MIN_JUGADORES = 2

# --- VALORES DE CASILLAS ESPECIALES ---
# Tesoros y Recursos
ENERGIA_TESORO_MENOR = 70
ENERGIA_TESORO_MAYOR = 120
ENERGIA_POZO_PM = 0
ENERGIA_CHATARRERIA_COSTO = -50

# Trampas y Daño
ENERGIA_TRAMPA = -60
ENERGIA_TRAMPA_PELIGROSA = -150
ENERGIA_PEAJE = -75
ENERGIA_VAMPIRO_PORCENTAJE = 15  # 15%

# --- VALORES DE HABILIDADES (COSTO ENERGÍA) ---
# Ofensivas
COSTO_SABOTAJE = 90
COSTO_BOMBA = 60
COSTO_ROBO = 65
COSTO_TSUNAMI = 50
COSTO_FUGA = 35

# Defensivas
COSTO_ESCUDO = 80
COSTO_CURACION = 70
COSTO_INVISIBILIDAD = 50
COSTO_BARRERA = 45
COSTO_FASE = 25
COSTO_TRASPASO = 35

# Movimiento
COSTO_COHETE = 40
COSTO_INTERCAMBIO = 75
COSTO_RETROCESO = 40
COSTO_REBOTE = 45

# Control
COSTO_DADO_PERFECTO = 40
COSTO_MINA = 35
COSTO_DOBLE_TURNO = 100
COSTO_CAOS = 50
COSTO_BLOQUEO = 55
COSTO_SOBRECARGA = 50
COSTO_TIRON = 30
COSTO_CONTROL_TOTAL = 90

# --- VALORES DE EFECTOS DE HABILIDADES ---
VALOR_CURACION = 150
DANO_BOMBA = 75
DANO_FUGA_DOT = 25
DURACION_FUGA = 3 
DURACION_ESCUDO_RONDAS = 3
DURACION_BLOQUEO_RONDAS = 2

# --- COSTOS DE PERKS (PM) ---
COSTO_PACK_BASICO = 4
COSTO_PACK_INTERMEDIO = 8
COSTO_PACK_AVANZADO = 12

# --- RECOMPENSAS Y BONUS ---
XP_POR_PARTIDA = 50
XP_VICTORIA = 25 
XP_MAESTRIA_BASE = 50
XP_MAESTRIA_VICTORIA = 100 

BONUS_EXPLORADOR = 100
RECOMPENSA_CAZA_ENERGIA = 50
RECOMPENSA_CAZA_PM = 2