"""Migracion inicial

Revision ID: ebbfa2fbc648
Revises:
Create Date: 2026-06-25 16:34:56.570068

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ebbfa2fbc648"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("private_message", schema=None) as batch_op:
        batch_op.create_index(
            "idx_pm_conversation",
            ["sender_id", "recipient_id", "timestamp"],
            unique=False,
        )
        batch_op.create_index(
            "idx_pm_conversation_rev",
            ["recipient_id", "sender_id", "timestamp"],
            unique=False,
        )
        batch_op.create_index(
            "idx_pm_unread", ["recipient_id", "read", "sender_id"], unique=False
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("user_email_key"), type_="unique")
        batch_op.drop_constraint(batch_op.f("user_username_key"), type_="unique")
        batch_op.drop_index(batch_op.f("ix_user_email"))
        batch_op.create_index(batch_op.f("ix_user_email"), ["email"], unique=True)
        batch_op.drop_index(batch_op.f("ix_user_username"))
        batch_op.create_index(batch_op.f("ix_user_username"), ["username"], unique=True)
        batch_op.create_index("idx_user_level_xp", ["level", "xp"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index("idx_user_level_xp")
        batch_op.drop_index(batch_op.f("ix_user_username"))
        batch_op.create_index(
            batch_op.f("ix_user_username"), ["username"], unique=False
        )
        batch_op.drop_index(batch_op.f("ix_user_email"))
        batch_op.create_index(batch_op.f("ix_user_email"), ["email"], unique=False)
        batch_op.create_unique_constraint(
            batch_op.f("user_username_key"),
            ["username"],
            postgresql_nulls_not_distinct=False,
        )
        batch_op.create_unique_constraint(
            batch_op.f("user_email_key"), ["email"], postgresql_nulls_not_distinct=False
        )

    with op.batch_alter_table("private_message", schema=None) as batch_op:
        batch_op.drop_index("idx_pm_unread")
        batch_op.drop_index("idx_pm_conversation_rev")
        batch_op.drop_index("idx_pm_conversation")

    # ### end Alembic commands ###
